development:
  adapter: postgresql
  encoding: unicode
  database: go_development
  pool: 5
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: go_test
  pool: 5
  host: localhost
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: go_production
  pool: 5
  username: go
  password:
